### ISSUE TITLE
How to extract JSON with quantities

### ISSUE THREAD

**Issue by BrunoMBuzzi** [xBimTeam/XbimExchange#46]
Hello there,

After researching for the pastcouple days, I've figure it out it would be better if I seek for your help here...

I've got to the point where I've implemented a solution next to this one.
https://github.com/xBimTeam/XbimEssentials/issues/94#issuecomment-313386981

But then, after creating the JSON, it seems there's no quantity data at all on this file.
Is there any way I could create this JSON with more dataon the elements? If yes, how could I do that, please?

Thanks,
Bruno.

**Comment by andyward** [comment]
Can you share what you expect? What 'quantity data' did you want to see. (There's lots of ways of conveying quantities in a model)

**Comment by BrunoMBuzzi** [comment]
Hello @andyward ,

I would like to know if there's a way to extract the JSON with the exchanger including more data on each element, like material, properties and quantities.

I would like to get the same data that is shown in the Xbim Xplorer, but in JSON.

![image](https://user-images.githubusercontent.com/39279756/61896266-f9522000-aeea-11e9-9e16-03a661c8b68c.png)


Thanks,
Bruno

**Comment by andyward** [comment]
How are you extracting the JSON? Are you using COBieLiteUK Exchanger or something else?

If you are, it should be outputting quantities. i.e. this code

https://github.com/xBimTeam/XbimExchange/blob/261d31c95c736158a7289a3c9e0e5762ad464695/Xbim.Exchanger/IfcToCOBieLiteUK/XbimAttributedObject.cs#L452

If it's not can you provide a repo with:

1) The IFC model
2) The code you're using to generate the JSON

Worth noting that as a simpler schema, the JSON representation is always going to be a lossy version of the IFC, so not everything will make it through the exchange. I can't remember off hand if materials make the cut, but quantities should.

**Comment by BrunoMBuzzi** [comment]
I was using this code:
`var facilities = new List<Facility>();
var exchanger= new IfcToCOBieLiteUkExchanger(model, facilities);
facilities = exchanger.Convert();

//there might be more than one facilities in theory but 
//COBie is only designed to hold a single building in a file.
for(var i = 0; i < facilities.Count; i++)
{
    var facility = facilities[i];
    var file = $"facility_{i}.json";
    facility.WriteJson(file);
}`

But in the converted JSON there was no quantity information on many elements. Even opening on a text editor and manually searching, there wasn't a single element with Volume, which is a quantity that is shown when I open the IFC on the Xbim Xplorer.

**Comment by andyward** [comment]
Can you provide a model? 
Are you expecting the Facility to have a volume, or are you looking for it on a Space?

**Comment by mmmggg** [comment]
The code above is throwing an exception when trying to generate the JSON for the attached IFC file.

The exception is:
```csharp
Exception: Object reference not set to an instance of an object.,    at XbimExchanger.IfcToCOBieLiteUK.XbimAttributedObject.GetAttributeValue(IIfcPropertyBoundedValue ifcPropertyBoundedValue)
   at XbimExchanger.IfcToCOBieLiteUK.XbimAttributedObject.ConvertToAttributeType(IIfcProperty ifcProperty)
   at XbimExchanger.IfcToCOBieLiteUK.CoBieLiteUkHelper.GetAttributes(IIfcObjectDefinition ifcObjectDefinition)
   at XbimExchanger.IfcToCOBieLiteUK.MappingIfcBuildingToFacility.Mapping(IIfcBuilding ifcBuilding, Facility facility)
   at XbimExchanger.IfcToCOBieLiteUK.IfcToCOBieLiteUkExchanger.Convert()
```

The code is:
```csharp
 using (var model = IfcStore.Open(sFilePathName))
{
      var facilities = new List<Facility>();
      var exchanger = new IfcToCOBieLiteUkExchanger(model, facilities);
      facilities = exchanger.Convert();
      var jsonFilename = Path.ChangeExtension(sFilePathName, "json");

      for (var i = 0; i < facilities.Count; i++)
      {
            var facility = facilities[i];
            var file = $"{sFilePathName}_{i}.json";

            if (facilities.Count == 1)
                        file = $"{sFilePathName}.json";

            facility.WriteJson(file);
      }
}
```
[test02.zip](https://github.com/xBimTeam/XbimExchange/files/3559896/test02.zip)

Can you, please, have a look at the attached file? Is there something wrong with it?

Thank  you!

**Comment by mmmggg** [comment]
Dear Andy,

is there a fix for the issue above? Will checking for null inside the `GetAttributeValue` and returning null be enough?

Thank you.

**Comment by dumitrugrl** [comment]
Hi,
I am trying to generate json from an IFC file and still getting this exception:
```
		Message	"Object reference not set to an instance of an object."	string
		SerializationStackTraceString	"   at XbimExchanger.IfcToCOBieLiteUK.XbimAttributedObject.GetAttributeValue(IIfcPropertyBoundedValue ifcPropertyBoundedValue)"	string
		StackTrace	"   at XbimExchanger.IfcToCOBieLiteUK.XbimAttributedObject.GetAttributeValue(IIfcPropertyBoundedValue ifcPropertyBoundedValue)"	string
		TargetSite	{Xbim.CobieLiteUk.AttributeValue GetAttributeValue(Xbim.Ifc4.Interfaces.IIfcPropertyBoundedValue)}	System.Reflection.MethodBase {System.Reflection.RuntimeMethodInfo}

```
I am guessing that it has to do with these lines in the IFC:
```
#100= IFCPROPERTYBOUNDEDVALUE('RentalRatesInCategoryNow',$,$,$,$);
#101= IFCPROPERTYSINGLEVALUE('VacancyRateInCategoryFuture',$,IFCPOSITIVERATIOMEASURE(0.),$);
#102= IFCPROPERTYBOUNDEDVALUE('RentalRatesInCategoryFuture',$,$,$,$);
```

The code I am using is the ones in the samples:
```
string folder = Path.GetDirectoryName(sFilePath);
string fileNameWithoutExtension = Path.GetFileNameWithoutExtension(sFilePath);                        

var facilities = new List<Facility>();
var exchanger = new IfcToCOBieLiteUkExchanger(model2, facilities);
facilities = exchanger.Convert();

var facilityType = facilities.FirstOrDefault();
if (facilityType == null)
  return;

facilityType.WriteJson(Path.Combine(folder, $"{fileNameWithoutExtension}.json"), true);string folder = Path.GetDirectoryName(sFilePath);
string fileNameWithoutExtension = Path.GetFileNameWithoutExtension(sFilePath);                        

var facilities = new List<Facility>();
var exchanger = new IfcToCOBieLiteUkExchanger(model2, facilities);
facilities = exchanger.Convert();

var facilityType = facilities.FirstOrDefault();
if (facilityType == null)
  return;

facilityType.WriteJson(Path.Combine(folder, $"{fileNameWithoutExtension}.json"), true);
```

Is there something I am missing?

Thank you!
